### ISSUE TITLE
Ruby SDK not working with edge URL

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/meilisearch-ruby#522] opened 2024-02-22 11:35 UTC
**Description**
Description of what the bug is about.
When using the edge URL with the ruby SDK, the following error is returned:

`validate': 500 Internal Server Error - MeiliSearch API has not returned any error message. See <no documentation link found>. (MeiliSearch::ApiError)`

This doesn't happen when using CURL.

It has been [reported by a Cloud customer](https://app.crisp.chat/website/38a71dd2-729c-4970-b061-3e1db1c1eb20/inbox/session_46c10229-0500-4213-ae20-bac82ef3d4ee/)  (private link) and I have reproduced it.

I have tried getting the stats and health.

**Expected behavior**
What you expected to happen.
When I get the health endpoiunt it should return:
`{"status":"available"}` which is what it returns when using cURL.

**Current behavior**
What happened.
```
/Users/carolina/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/meilisearch-0.27.0/lib/meilisearch/http_request.rb:131:in `validate': 500 Internal Server Error - MeiliSearch API has not returned any error message. See <no documentation link found>. (MeiliSearch::ApiError)
        from /Users/carolina/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/meilisearch-0.27.0/lib/meilisearch/http_request.rb:116:in `send_request'
        from /Users/carolina/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/meilisearch-0.27.0/lib/meilisearch/http_request.rb:26:in `http_get'
        from /Users/carolina/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/meilisearch-0.27.0/lib/meilisearch/client.rb:105:in `health'
        from index.rb:5:in `<main>'
```
**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Meilisearch version: [e.g. v.0.20.0]
- meilisearch-ruby version: [e.g v0.15.3]

**Comment by brunoocasali** [comment] 2024-02-22 14:10
The issue was found but not completely related to this gem. The ruby implementation was "lucky" enough to send `"null"` as a body even in `GET` requests, which were not allowed by our edge.meilisearch.com. 
So, I fixed the root cause. We may still want to fix it in the future, but we're not changing anything here right now.

Closing this issue! Feel free to reopen if needed.

**Closed by brunoocasali** 2024-02-22 14:10 UTC

**Comment by ellnix** [comment] 2024-02-22 14:15
It looks like the reason for passing null as the body is that body gets converted to JSON before `compact` runs in `http_config`:
https://github.com/meilisearch/meilisearch-ruby/blob/dcc99be1be5b2d2bbcca8516336988bf34814e42/lib/meilisearch/http_request.rb#L120
