### ISSUE TITLE
Error when calling "client.get_or_create_index" & index already exists

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/meilisearch-ruby#99] opened 2020-10-07 16:48 UTC
In Rails project, I call that method "client.get_or_create_index ('posts')" as an after_create callback in my model. So each time a new instance is saved in the DB, it is also indexed by meilisearch.
When I create the first instance in console, I get no errors (index doesn't exist yet). But, when I try to create a second instance, I get the following error : 

MeiliSearch::ApiError (MeiliSearch::ApiError - code:  - type:  - message: Impossible to create index; index already exists - link: <no documentation link found>)

**Comment by curquiza** [comment] 2020-10-08 14:49
Hello @CaroFG 
I've tried, and I'm not able to reproduce your issue.

```bash
$ rails new rails-test
$ cd rails-test
$ bundle install meilisearch
$ rails g scaffold post
$ rails db:create db:migrate
```

Then in `app/controllers/posts_controller.rb`

```ruby
require 'meilisearch'

class PostsController < ApplicationController

  ...

  # GET /posts
  def index
    client = MeiliSearch::Client.new('http://127.0.0.1:7700')
    index = client.get_or_create_index('movies')

    @posts = Post.all

    render json: @posts
  end

  ...

end
```

Run the rails server:

```bash
$ rails s
```

Run the MeiliSearch instance:

```bash
$ docker run -it --rm  -p 7700:7700 getmeili/meilisearch:v0.15.0 ./meilisearch  --no-analytics=true
```

Try it:

```bash
$ curl localhost:3000/posts
[]
$ curl localhost:3000/posts
[]
$ curl localhost:3000/posts
[]
```

=> I never get the exception

And the index is well created:

```bash
$ curl localhost:7700/indexes
[{"name":"movies","uid":"movies","createdAt":"2020-10-08T14:42:52.070922900Z","updatedAt":"2020-10-08T14:42:52.070985700Z","primaryKey":null}]⏎
```

**Comment by curquiza** [comment] 2020-10-12 08:58
Closing this issue then

**Closed by curquiza** 2020-10-12 08:58 UTC
Labels: SDK Ruby
